### PR TITLE
.signOut improvements

### LINKED ISSUE #1410: The signout function puts a default postLogoutRedirectUri when it's not passed
### Describe the bug

As per https://developer.okta.com/docs/guides/sign-users-out/nodeexpress/main/, it's totally valid to not pass `postLogoutRedirectUri`, however, the [`signOut` function defaults to window.location.origin](https://github.com/okta/okta-auth-js/blob/f1b59e49b0f46745c5cb0beffefa2af8bf712d40/lib/oidc/mixin/index.ts#L288-L292) when it's not passed which causes issues as it's not whitelisted.

### Reproduction Steps?

1. Call signOut function
`await oktaAuth.signOut({
      idToken: { idToken: logoutQueryParams.idToken }, 
      state: logoutQueryParams.state,
    });`
2. Shows error, that URL is not whitelisted but it should Okta signin page as per documentation.

### SDK Versions

  System:
    OS: macOS 13.3.1
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 20.72 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 14.21.1 - ~/.nvm/versions/node/v14.21.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v14.21.1/bin/yarn
    npm: 8.13.2 - ~/node_modules/.bin/npm
  Browsers:
    Chrome: 113.0.5672.126
    Firefox: 113.0.1
    Safari: 16.4
  npmPackages:
    @okta/okta-auth-js: ^6.9.0 => 6.9.0
    @okta/okta-react: ^6.7.0 => 6.7.0

### Additional Information?

_No response_

### PR DESCRIPTION
**Pull request by jaredperreault-okta**
Resolves #1410 and #1433

- allows for `postLogoutRedirectUri` to be `null` to invoke default `/logout` redirect behavior
- returns `state` as query param to redirect uri when `.signOut` falls back to `.closeSession`

### CODE REVIEW

File: lib/oidc/types/api.ts [hunk 1]
```diff
@@ -101,7 +101,7 @@ export interface IsAuthenticatedOptions {
 }
 
 export interface SignoutRedirectUrlOptions {
-  postLogoutRedirectUri?: string;
+  postLogoutRedirectUri?: string | null;
```
Comment (shuowu-okta) [inline lib/oidc/types/api.ts:104]: is null needed here as it's already optional?

File: lib/oidc/mixin/index.ts [hunk 2]
```diff
@@ -261,7 +261,7 @@ export function mixinOAuth
       if (!idToken) {
         return '';
       }
-      if (!postLogoutRedirectUri) {
+      if (postLogoutRedirectUri === undefined) {
```
[the remark this answers is not in the document]
Comment (shawyu-okta) [reply lib/oidc/mixin/index.ts:264]: nit: not likely a real issue but I prefer to check `typeof foo === 'undefined'`

File: lib/oidc/mixin/index.ts [hunk 3]
```diff
@@ -321,15 +328,18 @@ export function mixinOAuth
...
-          }
-          return sessionClosed;
-        });
+        const sessionClosed = await this.closeSession();   // can throw if the user cannot be signed out
+        const redirectUri = new URL(postLogoutRedirectUri || defaultUri); // during fallback, redirectUri cannot be null
+        if (state) {
+          redirectUri.searchParams.append('state', state);
+        }
+        if (postLogoutRedirectUri === currentUri) {
+          // window.location.reload(); // force a hard reload if URI is not changing
```
Comment (shawyu-okta) [inline lib/oidc/mixin/index.ts:337]: Can this commented code be removed?

File: lib/oidc/mixin/index.ts [hunk 4]
```diff
@@ -285,16 +285,23 @@ export function mixinOAuth
...
+      const currentUri = window.location.href;
+      // Fix for issue/1410 - allow for no postLogoutRedirectUri to be passed, resulting in /logout default behavior
+      //    "If no Okta session exists, this endpoint has no effect and the browser is redirected immediately to the
+      //    Okta sign-in page or the post_logout_redirect_uri (if specified)."
+      // - https://developer.okta.com/docs/reference/api/oidc/#logout
+      const postLogoutRedirectUri = options.postLogoutRedirectUri === null ? null :
+        (options.postLogoutRedirectUri
         || this.options.postLogoutRedirectUri
-        || defaultUri;
+        || defaultUri);
```
Comment (shawyu-okta) [inline lib/oidc/mixin/index.ts:297]: Be careful -- `options` vs `this.options`. Is there a difference? Maybe a different variable name would help avoid confusion.

File: test/spec/OktaAuth/browser.ts [hunk 5]
```diff
@@ -247,7 +247,7 @@ describe('OktaAuth (browser)', function() {
             expect(auth.revokeRefreshToken).toHaveBeenCalledWith(refreshToken);
             expect(auth.closeSession).not.toHaveBeenCalled();
             expect(window.location.assign).toHaveBeenCalledWith(`${issuer}/oauth2/v1/logout?id_token_hint=${idToken.idToken}&post_logout_redirect_uri=${encodedOrigin}`);
-            expect(signOutSuccess).toBeTruthy();
+            expect(signOutSuccess).toBe(true);
```
Comment (shawyu-okta) [inline test/spec/OktaAuth/browser.ts:250]: 👌

File: test/spec/OktaAuth/browser.ts [hunk 6]
```diff
@@ -197,7 +197,7 @@ describe('OktaAuth (browser)', function() {
     let encodedOrigin;
   
     beforeEach(function() {
-      origin = 'https://somesite.local';
+      origin = 'https://somesite.local/';
       href = `${origin}/some-route`;
```
Comment (shawyu-okta) [inline test/spec/OktaAuth/browser.ts:201]: idk if this matters but `href` will have a double-`/` with the change here

File: test/spec/OktaAuth/browser.ts [hunk 7]
```diff
@@ -389,8 +396,8 @@ describe('OktaAuth (browser)', function() {
             expect(auth.tokenManager.getTokensSync).toHaveBeenCalledTimes(4);
             expect(auth.revokeAccessToken).toHaveBeenCalledWith(accessToken);
             expect(auth.closeSession).toHaveBeenCalled();
-            expect(window.location.reload).toHaveBeenCalled();
-            expect(signOutSuccess).toBeTruthy();
+            // expect(window.location.reload).toHaveBeenCalled();   // TODO: confirm href?
```
Comment (shawyu-okta) [inline test/spec/OktaAuth/browser.ts:399]: 👀
